version: '2.1'
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
orbs:
  codecov: codecov/codecov@3.2.5
  node: circleci/node@4.7.0
workflows:
  upload-to-codecov:
    jobs:
      - node/test:
          post-steps:
            - codecov/upload
