version: '2.1'

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  upload-to-codecov:
    jobs:
      - build-and-test
      - codecov/upload:
          requires:
            - build-and-test

orbs:
  codecov: codecov/codecov@3.2.5
