version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.5
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: "a922317b-2ff3-42f8-96ea-d7fdabd58dde"

workflows:
  sample:
    jobs:
      - build-and-test
